### ISSUE TITLE
Safari 5.1.7 for Mac OS X Snow Leopard issue

### ISSUE THREAD

**Issue by erickpatrick** [soulwire/Makisu#7]
When opening the opening example in Safari 5.1.7 for Mac OS X Snow Leopard, it says it didn't detected CSS 3 capabilities.

![Problem with Safari 5.1.7](http://d3j5vwomefv46c.cloudfront.net/photos/full/678969741.png?key=1280800&Expires=1351440880&Key-Pair-Id=APKAIYVGSUJFNRFZBBTA&Signature=aIA8DF2hpSa9ZqRh4vU3eylVXjfk1NUqfwkjnEgU1sZbeKHjeARtegx6kNL1vGO7ds-huVP8eWj2gpm46cUyygUVNa~hOexyd-X2dP6AetT7Bn-AwiDVRUoWyAUcG9g3jhiqMOdIfJXXXAxDsE9PCiNuaxkncfFvrUNj-KjEOBE_)

**Comment by chilicomputer** [comment]
var vendor = (function() { for ( var p in el.style ) if( re.test(p) ) return p.match(re)[0]; })() || '';

When using this to detect the vendor, it failed!
Since safari can't list all of the style attributes, "p in el.style" does not work. 
Dont know WTF....
Maybe another method to detect the vendor should be excuted.

**Comment by noornaj** [comment]
Safari 5.1.7 on Snow Leopard 10.6.8 throws a undetectable CSS3 error. Script seems to work tho.
